# Generated by Django 4.0.4 on 2022-06-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0004_navbar_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='navimg',
            new_name='indexnav',
        ),
    ]
