# Generated by Django 4.0.4 on 2022-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0005_rename_navimg_navbar_indexnav'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='aboutnav',
            field=models.ImageField(blank=True, null=True, upload_to='images/nav'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='categorynav',
            field=models.ImageField(blank=True, null=True, upload_to='images/nav'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='conatctnav',
            field=models.ImageField(blank=True, null=True, upload_to='images/nav'),
        ),
    ]
