# Generated by Django 4.0.4 on 2022-06-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0006_navbar_aboutnav_navbar_categorynav_navbar_conatctnav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='navbar',
        ),
    ]
