# Generated by Django 4.0.4 on 2022-06-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0008_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='categoryimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/category'),
        ),
    ]
