# Generated by Django 4.0.4 on 2022-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0009_manhwa_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhua',
            name='categoryimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/category'),
        ),
        migrations.AddField(
            model_name='manhua',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
