# Generated by Django 4.0.4 on 2022-06-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0011_manhua_type_manhwa_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpost',
            name='created_on',
        ),
    ]
