# Generated by Django 4.0.4 on 2022-06-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0012_remove_allpost_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
